# The rules below have been manually copied from @commitlint/config-conventional
# and match the v1.0.0 specification:
# https://www.conventionalcommits.org/en/v1.0.0/#specification
#
# You can remove them and uncomment the config below when the following issue is
# fixed: https://github.com/conventional-changelog/commitlint/issues/613
#
# extends:
#   - '@commitlint/config-conventional'

rules:
  subject-case:
    -   2
    -   never
    -   [sentence-case, start-case, pascal-case, upper-case]
  subject-empty: [2, never]
  subject-full-stop: [2, never, .]
  type-case: [2, always, lower-case]
  type-empty: [2, never]
  header-max-length: [1, always, 52]
  body-case: [2, always, sentence-case]
  body-max-line-length: [1, always, 72]
  body-leading-blank: [1, always]
  footer-leading-blank: [1, always]
  footer-max-line-length: [2, always, 100]
  type-enum:
    -   2
    -   always
    -   -   chore
        -   core
        -   ci
        -   feat
        -   fix
        -   docs
        -   style
        -   refactor
        -   perf
        -   test
        -   revert

help: |
  **Possible types**:
    `chore`:        A technical or preventative maintenance task.
    `core`:         Change build process, tooling or dependencies.
    `ci`:           Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
    `feat`:         Adds a new feature.
    `fix`:          Solves a bug.
    `docs`:         Adds or alters documentation.
    `style`:        Improves formatting, white-space.
    `refactor`:     Rewrites code without feature, performance or bug changes.
    `perf`:         Improves performance.
    `test`:         Adds or modifies tests.
    `revert`:       Changes that reverting other changes
