[tool.pdm]

[project]
name = "hdunim"
version = "0.0.1"
description = "Unimodality in High-Dimensional Euclidean Space"
authors = [
    {name = "Prodromos Kolyvakis", email = "prokolyvakis@gmail.com"},
]
dependencies = [
    "scikit-learn>=1.2.2",
    "diptest>=0.5.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "AGPL-3.0-or-later"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
