# Run only fast tests.

name: Tests

on: push

jobs:

    test_workflow:

        runs-on: ubuntu-latest

        steps:

        -   name: Checkout repository
            uses: actions/checkout@v3

        -   name: Install pdm
            run: |
                curl -sSL https://pdm-project.org/install-pdm.py | python3 -

        -   name: Setup Python
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'

        -   name: Install dependencies
            run: |
                pdm install -G test

        -   name: Run test suite
            run: |
                pdm run pytest -v --maxfail 2 tests
            timeout-minutes: 10
